### PR TITLE
Passing in file object as a parameter to the json transform function

### PR DESCRIPTION
**Pull request by izaaz**
We had a requirement where we needed to suffix the json attribute name with the file name and hence needed the file object passed to the transform function.

Thanks,
Izaaz

### CODE REVIEW

**Comment by thaggie** [comment]
Thanks, this looks interesting. 

I'm concerned about leaking the file object itself especially as it's probably different on different platforms. 

When I run via a test project (rather than via the unit tests) `basename` doesn't seem to exist for me (on OSX or Linux). 

I've had a cursory look over a couple of other plugins that work with the file names ([gulp-rename](https://www.npmjs.com/package/gulp-rename) and [gulp-filenames](https://www.npmjs.com/package/gulp-filenames)), they seem to use `path`, `base` and `relative` properties of the file - I haven't been able to locate API documentation that covers this. All three of those properties appear to be there on linux and OSX but I'm not in a position to test Windows - which I'm guessing is the platform you're using.

[gulp-filenames](https://github.com/JohnyDays/gulp-filenames/blob/master/index.coffee#L65) makes an object with just those properties which I think would be an appropriate pattern to follow for the second argument.

So something like:

```
return transformFn(data, {
  path: file.path, 
  relative: file.relative, 
  base: file.base}
);
```

**Comment by izaaz** [comment]
Makes sense! Thanks for testing this on OSX and Linux. I tried it out and I
see that they exist on Windows as well

File path : test/fixtures/input.json
File relative : input.json
File base : test/fixtures

I'll update this today and send out another pull request.

Thanks,
Izaaz

On Wed, Jun 22, 2016 at 10:08 PM, Tom Haggie notifications@github.com
wrote:

> Thanks, this looks interesting.
> 
> I'm concerned about leaking the file object itself especially as it's
> probably different on different platforms.
> 
> When I run via a test project (rather than via the unit tests) basename
> doesn't seem to exist for me (on OSX or Linux).
> 
> I've had a cursory look over a couple of other plugins that work with the
> file names (gulp-rename https://www.npmjs.com/package/gulp-rename and
> gulp-filenames https://www.npmjs.com/package/gulp-filenames), they seem
> to use path, base and relative properties of the file - I haven't been
> able to locate API documentation that covers this. All three of those
> properties appear to be there on linux and OSX but I'm not in a position to
> test Windows - which I'm guessing is the platform you're using.
> 
> gulp-filenames
> https://github.com/JohnyDays/gulp-filenames/blob/master/index.coffee#L65
> makes an object with just those properties which I think would be an
> appropriate pattern to follow for the second argument.
> 
> So something like:
> 
> return transformFn(data, {
>   path: file.path,
>   relative: file.relative,
>   base: file.base}
> );
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/thaggie/gulp-json-transform/pull/4#issuecomment-227951228,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEMnK-eisy_W-cmkTrLA_O3rrTb5Rsj_ks5qOhTfgaJpZM4I8RLw
> .

## 

Izaaz Yunus

**Comment by izaaz** [comment]
Hi Tom,

I've updated the pull request with the change we discussed.

Thanks,
Izaaz

**Comment by thaggie** [comment]
Thanks - I've now merged the changes to master and cut a new version.

**Pull request merged**
